# Generated by Django 5.1.4 on 2026-07-03 17:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='importacoes/', verbose_name='arquivo CSV')),
                ('fornecedor', models.CharField(max_length=120, verbose_name='fornecedor')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('CONCLUIDA', 'Concluída'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20, verbose_name='status')),
                ('total_linhas', models.PositiveIntegerField(default=0, verbose_name='total de linhas')),
                ('linhas_criadas', models.PositiveIntegerField(default=0, verbose_name='linhas criadas')),
                ('linhas_atualizadas', models.PositiveIntegerField(default=0, verbose_name='linhas atualizadas')),
                ('erros', models.JSONField(blank=True, default=list, verbose_name='erros')),
                ('detalhe', models.TextField(blank=True, verbose_name='detalhe')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'importação de catálogo',
                'verbose_name_plural': 'importações de catálogo',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=200, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='preço')),
                ('quantidade', models.PositiveIntegerField(default=0, verbose_name='quantidade disponível')),
                ('fornecedor', models.CharField(db_index=True, help_text='Catálogo/fornecedor de origem da peça.', max_length=120, verbose_name='fornecedor')),
                ('estoque_minimo', models.PositiveIntegerField(default=5, help_text='Abaixo deste nível a peça é reposta pelo cronjob.', verbose_name='estoque mínimo')),
                ('estoque_alvo', models.PositiveIntegerField(default=20, help_text='Nível para o qual a peça é reposta pelo cronjob.', verbose_name='estoque alvo')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'peça',
                'verbose_name_plural': 'peças',
                'ordering': ['nome', 'fornecedor'],
                'constraints': [models.UniqueConstraint(fields=('nome', 'fornecedor'), name='uniq_peca_nome_fornecedor')],
            },
        ),
    ]
