# Generated by Django 5.1.4 on 2026-07-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_pg_trgm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peca',
            name='estoque_alvo',
        ),
        migrations.AddField(
            model_name='peca',
            name='reposicao',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade a somar ao estoque. A task de reposição aplica e zera.', verbose_name='reposição pendente'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='estoque_minimo',
            field=models.PositiveIntegerField(default=5, help_text='Abaixo deste nível a peça é sinalizada como estoque baixo.', verbose_name='estoque mínimo'),
        ),
    ]
